### ISSUE TITLE
MagicLink import page should be able to adjust gas

### ISSUE THREAD

**Issue by zhangzhongnan928** [TokenScript/TokenScript#264]
https://etherscan.io/tx/0x51a5875c5e530ae0759766cb63e7e860c7dea8b93a8a927ee0dd7c1dbb82318e

Currently how does wallet calculate the gas used in MagicLink import page?

**Comment by hboon** [comment]
This should come when we implement the app-wide actionsheet (which replaces the current confirmation screen for sending Ether/tokens) which we can use for all transactions. Currently on a sprint to implement a UI refresh so future work (actionsheet next) can all be built on it.

> Currently how does wallet calculate the gas used in MagicLink import page?

A large number on iOS. I know...

**Comment by zhangzhongnan928** [comment]
Android gives a 1.2Gwei gas😂😂😂
Has been pending for more than 30mins.

**Comment by hboon** [comment]
@zhangzhongnan928 "Vote" this card up if it bothers you :)

https://trello.com/c/26MTjbSU/70-ask-a-user-i-want-to-be-able-to-cancel-override-speed-up-transactions-like-in-metamasks-so-i-am-not-stuck-with-a-transaction

**Comment by zhangzhongnan928** [comment]
It is the gas station(payment server) who send the transection. @James-Sangalli is it a fixed gas price?

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 no, it uses the gas fee recommended by the ethereum node. Currently it seems correct:

<img width="968" alt="Screen Shot 2019-11-04 at 10 48 29 am" src="https://user-images.githubusercontent.com/16630514/68094056-abd54e00-fef0-11e9-8615-8821dc1d968b.png">

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 we should be able to adjust gas when the user pays but not the gas fee of the paymaster, that just opens us up to attacks whereby a user can set the gas price to a huge sum and drain all the ether out of the account

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 we should be able to adjust gas when the user pays but not the gas fee of the paymaster, that just opens us up to attacks whereby a user can set the gas price to a huge sum and drain all the ether out of the account

agreed. at the beginning, I thought that tx is sent by Andriod. 
P.S. the paymaster works for FIFA.
