### ISSUE TITLE
Fix the FIFA Layout

### ISSUE THREAD

**Issue by zhangzhongnan928** [TokenScript/TokenScript#313]
Since we updated the layout constraints, the old FIFA layout is broken. We should fix it or use the new layout.

**Comment by tomekalphawallet** [comment]
@James-Sangalli please send me few more tickets to tomek.eth or colourfreak.eth

**Comment by tomekalphawallet** [comment]
<img width="815" alt="Screenshot 2020-01-03 at 11 29 42" src="https://user-images.githubusercontent.com/51817359/71718708-5cda6500-2e1c-11ea-829d-73d0b28a3232.png">

@James-Sangalli I used the same trick as with Unicon. So two large svgs, where the content is not editable. 

https://www.dropbox.com/sh/d4abq4it43qdph7/AACYC-WTi9NkzQTpG_Mf77xea?dl=0

**Comment by James-Sangalli** [comment]
Done by Aidan

**Comment by zhangzhongnan928** [comment]
![13437B09-94A7-4725-AB61-9FA0EDE2C8F4](https://user-images.githubusercontent.com/33795543/74096653-9a39bd00-4b55-11ea-96bb-4642a5842e9c.png)

There is no number of tickets, in this example, it should be 3 group total 7 tickets

**Comment by zhangzhongnan928** [comment]
![IMG_1842](https://user-images.githubusercontent.com/33795543/74202563-e9503100-4cc0-11ea-8484-e7581655b4f8.PNG)

Bug
3+9+1 = 13 not 7

**Comment by zhangzhongnan928** [comment]
And the maximum amount of tickets can be transferred in each group is wrong, but they are matching the total number 7
![IMG_1844](https://user-images.githubusercontent.com/33795543/74202711-67acd300-4cc1-11ea-8942-359dd998a2a4.PNG)
![IMG_1843](https://user-images.githubusercontent.com/33795543/74202713-68de0000-4cc1-11ea-81ac-39a64068d61a.PNG)

![IMG_1845](https://user-images.githubusercontent.com/33795543/74202704-611e5b80-4cc1-11ea-9e22-255fa1fda1e9.PNG)

**Comment by zhangzhongnan928** [comment]
https://etherscan.io/tx/0x4342958134c265ad91cbde30c27257e28628d84e558a89c0b60dc62d092b3610
and transection  fails.

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 first part is solved, now the number is correct: https://github.com/AlphaWallet/TokenScript-Examples/commit/c684de853aa758743a24921c3e6ba7a7939d82ce

kill the app and restart, you will see the corrected number.

**Comment by James-Sangalli** [comment]
The rest is an iOS issue, closing here.

**Comment by zhangzhongnan928** [comment]
The layout on an iPad is wrong
![IMG_0179](https://user-images.githubusercontent.com/33795543/74302160-97370a80-4da9-11ea-909e-67de55a661ad.PNG)

**Comment by tomekalphawallet** [comment]
@James-Sangalli Do you need a design for iPad?

**Comment by zhangzhongnan928** [comment]
> @James-Sangalli Do you need a design for iPad?

It should automatically adapt to screens of different sizes
