### ISSUE TITLE
Hitting refresh or opening same link again, creates a new ticket

### ISSUE THREAD

**Issue by AW-STJ** [TokenScript/TokenScript#410]
May be related to #409. 

I noticed that hitting refresh creates more tickets. This should not be the case, if same ticket link is opened multiple times it should still generate only one ticket.

@colourful-land - can you confirm whether this is the expected behaviour or not?

**Comment by nicktaras** [comment]
Hi @AW-STJ 

Thanks for raising this issue. It should be resolved in the merge of https://github.com/TokenScript/TokenScript/pull/411

**Comment by nicktaras** [comment]
I'll keep this open until we merge to ensure it has corrected the issue.

**Comment by AW-STJ** [comment]
Resolved in #411
